spring.application.name=habit-journal-api

## Se hace visible la consola de H2
#spring.h2.console.enabled=true
## Esta es la URL de la base de datos en memoria que Spring creó
#spring.datasource.url=jdbc:h2:mem:testdb
#spring.datasource.driverClassName=org.h2.Driver
#spring.datasource.username=sa
#spring.datasource.password=
## Le dice a Hibernate que "hable" en el dialecto de H2
#spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
## Mostrar consultas SQL en la consola
#spring.jpa.show-sql=true
## Formatea las consultas para su legibilidad
#spring.jpa.properties.hibernate.format_sql=true

spring.data.mongodb.uri=mongodb+srv://admin:my-local-secret-123@localhost/habit_journal_db?appName=HabitJournalCluster
spring.data.mongodb.database=habit_journal_db
