spring.application.name=habit-journal-api-hex

spring.data.mongodb.uri=mongodb+srv://admin:my-local-secret-123@localhost/habit_journal_db?appName=HabitJournalCluster
spring.data.mongodb.database=habit_journal_db
